import moment from "moment";

const host = window.location.origin;
var url = String(window.location.pathname);
export const getUserId = () => window.localStorage[`${host}_uid`] ?? "";
export const getTokens = () => window.localStorage?.[`${host}_tokens`] ?? "{}";
export const getUser = () => window.localStorage?.[`${host}_user`] ?? "{}";
export const setSessionCookies = (user) => {
  window.localStorage[`${host}_user`] = JSON.stringify(user.user);
  window.localStorage[`${host}_uid`] = user.user.id;
  window.localStorage[`${host}_token`] = JSON.stringify(user.token);
  window.localStorage[`${host}_uuid`] = JSON.stringify(user.token);
  //   window.localStorage[`${host}_refresh_time`] = JSON.stringify(
  //     newRefreshTokenTimeInterval
  //   );
  window.localStorage[`${host}_login_time`] = moment();
  window.localStorage[`${host}_login`] = "true";
};
export const colorArray = [
  "#FF6633",
  "#FFB399",
  "#FF33FF",
  "#FFFF99",
  "#00B3E6",
  "#E6B333",
  "#3366E6",
  "#999966",
  "#99FF99",
  "#B34D4D",
  "#80B300",
  "#809900",
  "#E6B3B3",
  "#6680B3",
  "#66991A",
  "#FF99E6",
  "#CCFF1A",
  "#FF1A66",
  "#E6331A",
  "#33FFCC",
  "#66994D",
  "#B366CC",
  "#4D8000",
  "#B33300",
  "#CC80CC",
  "#66664D",
  "#991AFF",
  "#E666FF",
  "#4DB3FF",
  "#1AB399",
  "#E666B3",
  "#33991A",
  "#CC9999",
  "#B3B31A",
  "#00E680",
  "#4D8066",
  "#809980",
  "#E6FF80",
  "#1AFF33",
  "#999933",
  "#FF3380",
  "#CCCC00",
  "#66E64D",
  "#4D80CC",
  "#9900B3",
  "#E64D66",
  "#4DB380",
  "#FF4D4D",
  "#99E6E6",
  "#6666FF",
];
export const languageArray = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bhojpuri",
  "Bosnian",
  "Bulgarian",
  "Burmese (Myanmar)",
  "Catalan",
  "Cebuano",
  "Chewa (Chichewa)",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dogri",
  "Dutch",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Guarani",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Ilocano",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Konkani",
  "Korean",
  "Krio",
  "Kurdish (Kurmanji)",
  "Kurdish (Sorani)",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luganda",
  "Luxembourgish",
  "Macedonian",
  "Maithili",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maldivian (Dhivehi)",
  "Maltese",
  "Māori (Maori)",
  "Marathi",
  "Meitei (Manipuri)",
  "Mizo",
  "Mongolian",
  "Nepali",
  "Northern Sotho (Sepedi)",
  "Norwegian (Bokmål)",
  "Odia (Oriya)",
  "Oromo",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi (Gurmukhi)",
  "Quechua",
  "Romanian",
  "Russian",
  "Samoan",
  "Sanskrit",
  "Scottish Gaelic",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho (Sesotho)",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog (Filipino)",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tigrinya",
  "Tsonga",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "West Frisian (Frisian)",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

export const unSetSessionCookies = () => {
  window.localStorage.removeItem(`${host}_user`);
  window.localStorage.removeItem(`${host}_uid`);
  window.localStorage.removeItem(`${host}_token`);
  window.localStorage.removeItem(`${host}_uuid`);
  window.localStorage.removeItem(`${host}_refresh_time`);
  window.localStorage.removeItem(`${host}_login_time`);
  window.localStorage.removeItem(`${host}_login`);
  window.localStorage.removeItem("start_date");
  window.localStorage.removeItem("end_date");
  window.localStorage.removeItem("currentPage");
};

export const setTokens = (tokens) => {
  window.localStorage[`${host}_tokens`] = JSON.stringify(tokens);
};
