import React from "react";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import RouteWithLayout from "./RouteWithLayout"; // Custom route with layout
import { Main, Minimal, Client } from "../layouts"; // layouts for pages/components
import {
  AccessDenied,
  Login,
  SignUp,
  ClientHome,
  ForgotPassword,
  Users,
  UserDetails,
  AdminVoice,
  VoiceDetail,
  PackageDetail,
  Packages,
  AddPackage,
  PaymentMethods,
  Settings,
  ClientDashboard,
  ClientPackage,
} from "../components"; // these are all pages

const MainRouting = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Navigate to="/login" />} />
        <Route
          path="/login"
          element={
            <RouteWithLayout path="/login" layout={Minimal} component={Login} />
          }
        />
        <Route
          path="/signUp"
          element={
            <RouteWithLayout
              path="/signUp"
              layout={Minimal}
              component={SignUp}
            />
          }
        />
        {/* <Route
          path="/admin/home"
          element={
            <RouteWithLayout
              path={"/admin/home"}
              layout={Main}
              component={"AdminHome"}
              protectedRoute={true}
            />
          }
        /> */}
        <Route
          path="/admin/users"
          element={
            <RouteWithLayout
              path={"/admin/users"}
              layout={Main}
              component={Users}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/user-details/:userId"
          element={
            <RouteWithLayout
              path={"/admin/user-details/:userId"}
              layout={Main}
              component={UserDetails}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/packages"
          element={
            <RouteWithLayout
              path={"/admin/packages"}
              layout={Main}
              component={Packages}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/add/package"
          element={
            <RouteWithLayout
              path={"/admin/add/package"}
              layout={Main}
              component={AddPackage}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/packages/:packageId"
          element={
            <RouteWithLayout
              path={"/admin/packages/:packageId"}
              layout={Main}
              component={PackageDetail}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/voices"
          element={
            <RouteWithLayout
              path={"/admin/voices"}
              layout={Main}
              component={AdminVoice}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/voices/details"
          element={
            <RouteWithLayout
              path={"/admin/voices/details"}
              layout={Main}
              component={VoiceDetail}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/admin/payments"
          element={
            <RouteWithLayout
              path={"/admin/payments"}
              layout={Main}
              component={PaymentMethods}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/client/home"
          element={
            <RouteWithLayout
              path={"/client/home"}
              layout={Client}
              component={ClientHome}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/client/dashboard"
          element={
            <RouteWithLayout
              path={"/client/dashboard"}
              layout={Client}
              component={ClientDashboard}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/client/package"
          element={
            <RouteWithLayout
              path={"/client/package"}
              layout={Client}
              component={ClientPackage}
              protectedRoute={true}
            />
          }
        />

        <Route
          path="/settings"
          element={
            <RouteWithLayout
              path={"/settings"}
              layout={Main}
              component={Settings}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/forgot-password"
          element={
            <RouteWithLayout
              path={"/forgot-password"}
              layout={Main}
              component={ForgotPassword}
              protectedRoute={true}
            />
          }
        />
        <Route
          path="/access-denied"
          element={
            <RouteWithLayout
              path={"/access-denied"}
              layout={Main}
              component={AccessDenied}
              protectedRoute={true}
            />
          }
        />
        <Route path="/not-found" element={<h1>Not Found</h1>} />
        <Route path="*" element={<Navigate to="/not-found" />} />
        {/* <Navigate to="/not-found" /> */}
      </Routes>
    </BrowserRouter>
  );
};

export default MainRouting;
